language: julia
os:
    - linux
julia:
    - release
    - nightly
notifications:
    email: false
sudo: false
addons:
    apt_packages:
        - gfortran
        - liblapack-dev
        - libgmp-dev
        - libglpk-dev
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.add("JuMP"); Pkg.add("JuMPeR")'
    - julia -e 'Pkg.clone(pwd())'
    - julia -e 'Pkg.test("DDUS", coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("DDUS")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
